In [2]:
import numpy as np

In [3]:
a=np.matrix(np.ones((5,5)))
np.asarray(a)[1][1]=0
np.asarray(a)[1][2]=0
np.asarray(a)[1][3]=0
np.asarray(a)[2][1]=0
np.asarray(a)[2][2]=9
np.asarray(a)[2][3]=0
np.asarray(a)[3][1]=0
np.asarray(a)[3][2]=0
np.asarray(a)[3][3]=0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [4]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
c=np.array([11,12,13,14,15])
d=np.array([16,17,18,19,20])
e=np.array([21,22,23,24,25])
f=np.array([26,27,28,29,30])
z=np.vstack((a,b,c,d,e,f))
print(z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [5]:
print(z[[0],[3,4]],z[[4],[3,4]],z[[5],[3,4]])
print(z[[2],[0,1]],z[[3],[0,1]])
print(z.diagonal(1))

[4 5] [24 25] [29 30]
[11 12] [16 17]
[ 2  8 14 20]
